require 'rake'
require 'rspec/core/rake_task'

task :default => :spec

RSpec::Core::RakeTask.new(:spec) do |t|
t.pattern = Dir.glob('spec/*_spec.rb')
t.rspec_opts = '--format documentation'
end

namespace :run_trivia do
  desc "Data Types and Variables Trivia Challenge"
  task :"1" => [] do
    ruby "trivia/01_data_types_and_variables/runner.rb"
  end

  desc "Methods Trivia Challenge"
  task :"2" => [] do
    ruby "trivia/02_methods/runner.rb"
  end
end

namespace :run_lab do
  desc "Lab I: Mad lib statements in Sinatra"
  task :"1" => [] do
    ruby "labs/01_data_types_and_variables/runner.rb"
  end

  task :"2" => [] do
    ruby "labs/02_methods/runner.rb"
  end
end
